model:
  confidence_threshold: 0.25
  img_size: 960
  weights_path: weights/best.pt
video:
  output_path: Data/test_videos/output_test_1.mp4
  show_window: false
  source_path: Data/test_videos\green and red.mp4
